create nav and landing for Homepage and add css
GSG-CF05/fashion-app-team-8 pull request #6
Opened 2022-02-07 17:23 UTC by MohammedShorafa

relate #5

2022-02-07 18:51 UTC, sara219 requested changes
create an assets folder for the project, and inside it create another one for the home page and put the image inside it 

```
|----assets/
       |____home-page/
                 |___basic-photo.png
```

2022-02-08 16:33 UTC, hussamshahla submitted a review, later dismissed

2022-02-09 08:21 UTC, sara219 submitted a review, later dismissed

2022-02-09 11:12 UTC, Jomanahani approved these changes

2022-02-09 13:14 UTC, sara219 approved these changes

2022-02-09 14:16 UTC, merged